### ISSUE TITLE
NavBar styles does not match the design

### ISSUE THREAD

**Issue by karthiknmenon** [Eileen30/Front-End-Test#1]
Expected Design - 
![image](https://user-images.githubusercontent.com/41678651/106847449-ec63de80-66d4-11eb-8df2-ed90aad4c622.png)

Current design in deployed app- 
![image](https://user-images.githubusercontent.com/41678651/106847426-df46ef80-66d4-11eb-9a9e-a45e5264a095.png)

@Eileen30, check the expected design of `navbar` and work on the following - 

- [x] Font weight and colors should match as that of the design 
- [x] Padding of `navbar` in design is different compared to that of the deployed app 
- [x] The bootstrap button needs to be custom styled to that of the design (colors, font-weight, dimensions)
- [x] Current `navbar` in deployed app is not full width, it needs to be full width 
- [x] There is a `border-bottom` in the design for navbar

While doing these changes, please create a new branch with the issue number, like - `01-navbar-styles-update`

**Comment by eileenninan** [comment]
I have merged the code
